name: Go test trzsz-go
on: [push]
jobs:
  go-test-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout trzsz-go
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - name: go test
        run: go test -v -count=1 ./trzsz
  go-test-on-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout trzsz-go
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - name: go test
        run: go test -v -count=1 ./trzsz
  go-test-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout trzsz-go
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - name: go test
        run: go test -v -count=1 ./trzsz
  go-release-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout trzsz-go
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v1"
          args: release --clean --snapshot --skip=publish
